# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.cache/wt} [current_project]
set_property parent.project_path {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.srcs/sources_1/imports/sources_1/imports/FITXATEGIAK/kcuart_tx.vhd}
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.srcs/sources_1/imports/sources_1/new/TopDesign.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.srcs/constrs_1/imports/logicos_bi_aldia/Constraint.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/Demo_mandar_Tx/Demo_mandar_Tx.srcs/constrs_1/imports/logicos_bi_aldia/Constraint.xdc}}]


synth_design -top TopDesign -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TopDesign.dcp

catch { report_utilization -file TopDesign_utilization_synth.rpt -pb TopDesign_utilization_synth.pb }
