# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7a35tcpg236-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.cache/wt} [current_project]
set_property parent.project_path {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/sources_1/imports/sources_1/imports/UART_controller_files/UART.vhd}
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/sources_1/imports/sources_1/imports/UART_controller_files/UART_rx.vhd}
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/sources_1/imports/sources_1/imports/UART_controller_files/UART_tx.vhd}
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/sources_1/imports/sources_1/imports/UART_controller_files/button_debounce.vhd}
  {C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/sources_1/imports/sources_1/imports/UART_controller_files/UART_controller.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/constrs_1/imports/constrs_1/imports/UART_controller_files/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/constrs_1/imports/constrs_1/imports/UART_controller_files/constraints.xdc}}]

read_xdc {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/constrs_1/imports/constrs_1/new/main.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/mikel/Desktop/proyecto/producto/Sistemas logicos programables/PruebaTx/PruebaTx.srcs/constrs_1/imports/constrs_1/new/main.xdc}}]


synth_design -top UART_controller -part xa7a35tcpg236-1I


write_checkpoint -force -noxdef UART_controller.dcp

catch { report_utilization -file UART_controller_utilization_synth.rpt -pb UART_controller_utilization_synth.pb }
